apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: user-platform-exam
  labels:
    app: autoexam
    component: ui-config
    tier: platform
    version: v1
data:
  LOGIN_TITLE: "Вход в систему"
  REGISTER_TITLE: "Создайте аккаунт"
  WELCOME_MESSAGE: "Добро пожаловать в Autoexam"
