apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: user-platform-exam
  labels:
    app: autoexam
    component: finance
    tier: backend
    version: v1
spec:
  type: ClusterIP
  selector:
    app: autoexam
    component: finance
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  namespace: user-platform-exam
  labels:
    app: autoexam
    component: finance
    tier: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoexam
      component: finance
  template:
    metadata:
      labels:
        app: autoexam
        component: finance
        tier: backend
        version: v1
    spec:
      containers:
        - name: finance-service
          image: autoexam/finance-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_HOST
            - name: APP_PORT
              value: "8003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: AUTH_VALIDATE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_VALIDATE_URL
            - name: NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NOTIFICATION_URL
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
