apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: user-platform-exam
  labels:
    app: autoexam
    component: postgres
    tier: data
    version: v1
type: Opaque
stringData:
  POSTGRES_DB: autoexam
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
