apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: user-platform-exam
  labels:
    app: autoexam
    component: backend
    tier: platform
    version: v1
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres.user-platform-exam.svc.cluster.local:5432/autoexam
  JWT_SECRET: change-me
